// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "ChineseNewYear",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "ChineseNewYear",
            targets: ["AppModule"],
            bundleIdentifier: "com.RoyRao.ChineseNewYear",
            teamIdentifier: "S6ZX968578",
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            additionalInfoPlistContentFilePath: "Docs/Info.plist"
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .copy("Docs")
            ]
        )
    ]
)
